import type { Locale } from './i18n';

export const DISCORD_URL = 'https://discord.gg/V3m8pDe3wz';
export const COMMUNICATION_CONSENT_VERSION = 'product_updates_v1';

export const communityCopy: Record<Locale, {
  discord:string; title:string; body:string; betaTitle:string; betaBody:string; dismiss:string;
  emailTitle:string; emailBody:string; emailSave:string; emailOn:string; emailOff:string;
}> = {
  en:{discord:'Join the FantaFort Discord',title:'Build FantaFort with us',body:'Share beta feedback, report bugs, suggest features and discuss the game with the community.',betaTitle:'FantaFort is in beta',betaBody:'Tell us what works and what needs improvement in the official Discord.',dismiss:'Dismiss',emailTitle:'Receive FantaFort updates by email',emailBody:'We will occasionally send updates about the beta, new features, important changes and community initiatives. You can opt out at any time.',emailSave:'Save email preference',emailOn:'Email updates enabled.',emailOff:'Email updates disabled.'},
  it:{discord:'Entra nel Discord di FantaFort',title:'Costruiamo FantaFort insieme',body:'Lascia feedback sulla beta, segnala bug, proponi funzionalità e parla del gioco con la community.',betaTitle:'FantaFort è ancora in beta',betaBody:'Raccontaci cosa funziona e cosa migliorare nel Discord ufficiale.',dismiss:'Chiudi',emailTitle:'Ricevi aggiornamenti FantaFort via email',emailBody:'Ti invieremo occasionalmente comunicazioni sulla beta, nuove funzionalità, modifiche importanti e iniziative della community. Puoi disattivarle in qualsiasi momento.',emailSave:'Salva preferenza email',emailOn:'Aggiornamenti email attivati.',emailOff:'Aggiornamenti email disattivati.'},
  es:{discord:'Únete al Discord de FantaFort',title:'Construye FantaFort con nosotros',body:'Comparte opiniones sobre la beta, informa de errores, sugiere funciones y habla del juego con la comunidad.',betaTitle:'FantaFort está en beta',betaBody:'Cuéntanos qué funciona y qué debemos mejorar en el Discord oficial.',dismiss:'Cerrar',emailTitle:'Recibe novedades de FantaFort por correo',emailBody:'Enviaremos ocasionalmente novedades de la beta, nuevas funciones, cambios importantes e iniciativas de la comunidad. Puedes desactivarlas cuando quieras.',emailSave:'Guardar preferencia',emailOn:'Novedades por correo activadas.',emailOff:'Novedades por correo desactivadas.'},
  de:{discord:'Dem FantaFort-Discord beitreten',title:'Gestalte FantaFort mit uns',body:'Teile Beta-Feedback, melde Fehler, schlage Funktionen vor und diskutiere das Spiel mit der Community.',betaTitle:'FantaFort ist in der Beta',betaBody:'Sag uns im offiziellen Discord, was funktioniert und was wir verbessern sollen.',dismiss:'Schließen',emailTitle:'FantaFort-Updates per E-Mail erhalten',emailBody:'Wir senden gelegentlich Informationen zur Beta, neuen Funktionen, wichtigen Änderungen und Community-Aktionen. Du kannst sie jederzeit abbestellen.',emailSave:'E-Mail-Einstellung speichern',emailOn:'E-Mail-Updates aktiviert.',emailOff:'E-Mail-Updates deaktiviert.'},
  fr:{discord:'Rejoindre le Discord FantaFort',title:'Construisez FantaFort avec nous',body:'Partagez vos retours sur la bêta, signalez des bugs, proposez des fonctions et discutez du jeu avec la communauté.',betaTitle:'FantaFort est en bêta',betaBody:'Dites-nous ce qui fonctionne et ce qui doit être amélioré sur le Discord officiel.',dismiss:'Fermer',emailTitle:'Recevoir les actualités FantaFort par e-mail',emailBody:'Nous enverrons occasionnellement des informations sur la bêta, les nouveautés, les changements importants et les initiatives communautaires. Vous pouvez vous désinscrire à tout moment.',emailSave:'Enregistrer la préférence',emailOn:'Actualités par e-mail activées.',emailOff:'Actualités par e-mail désactivées.'},
};
