export type GuideLocale='en'|'it';
export type Guide={slug:string;title:string;description:string;sections:{title:string;paragraphs:string[]}[]};
export const guideSlugs=['fortnite-fantasy-league','fncs-scoring-guide','team-eliminations','player-eligibility','standings-and-projections','data-and-price-updates'] as const;

const en:Guide[]=[
 {slug:'fortnite-fantasy-league',title:'How a Fortnite Fantasy League Works',description:'A practical guide to drafting pro players, managing a virtual budget and scoring real FNCS tournament results.',sections:[
  {title:'The basic idea',paragraphs:['A Fortnite fantasy league turns competitive results into a private manager competition. Instead of playing the tournament, each manager recruits a roster of real pro players. Their official results generate fantasy points after the event begins.','FantaFort leagues are private and shared by invite code. The owner chooses the virtual budget, roster size, market duration, league duration and scoring mode. Players are exclusive within a league, which makes the draft a strategic race rather than a copy of everyone else’s roster.']},
  {title:'Drafting without retroactive points',paragraphs:['Managers recruit eligible players before an event. A score counts only when the tournament starts after the player was acquired. This prevents someone from buying yesterday’s winner and receiving points that were already earned.','The budget is virtual and cannot be bought or cashed out. A manager may reserve part of it for a captain or predictions, but those choices also lock before the relevant event.']},
  {title:'What decides the winner',paragraphs:['Official leaderboard points provide the base score. Depending on league settings, team points can be assigned in full, divided by team size or counted once per formation. Synergy and pre-event predictions add limited bonuses. The winner is the manager with the highest valid score when the league ends.']}]},
 {slug:'fncs-scoring-guide',title:'FNCS Fantasy Scoring Guide',description:'Learn how FantaFort converts official FNCS team points into classic, balanced and formation fantasy scores, with a worked duo example.',sections:[
  {title:'Start with the official leaderboard',paragraphs:['FantaFort does not recreate Fortnite scoring rules. It imports the points published for each official leaderboard entry, together with placement tiers, elimination rules and session history when the provider exposes them. That official total is the base for every fantasy mode.','The source row belongs to the official formation. In a duo or trio, each verified teammate is linked to the same team result. FantaFort changes only how a private league assigns that result; it does not alter the tournament total.']},
  {title:'Three ways to assign team points',paragraphs:['Classic mode gives the full official score to every rostered member of that formation. It is simple and rewards selecting any member of a successful duo or trio. Balanced mode divides the score by official team size for each selected player, reducing duplication. Formation mode groups selected teammates by official team and counts that formation once per manager.','No mode can reconstruct individual eliminations because the competitive leaderboard reports them at team level. Choosing a mode is therefore a league design decision, not a claim about who secured each elimination.']},
  {title:'Worked duo example',paragraphs:['Assume an official duo finishes with 240 points. If a manager selected both teammates, Classic produces 480 base points: 240 for each roster entry. Balanced produces 240 total: 240 divided by the duo size for each of the two selected players. Formation produces 240 because the official duo is counted once.','If the manager selected only one member, Classic produces 240, Balanced 120 and Formation 240. These are base-score examples before synergy, strategy bonuses or a verified penalty. The numbers are illustrative; the live page always uses the official imported total.']},
  {title:'Bonuses, projections and timing',paragraphs:['Captain adds 10% to the selected player. Teammate and exact-score predictions are capped, and all strategic picks lock at event start. Acquisitions after the start never receive points from that event.','A live projection may extend the current points-per-match pace to a known match cap. It is displayed separately and never replaces the official result used when scoring is final. Provider corrections can still update historical totals.']}]},
 {slug:'team-eliminations',title:'Why FNCS Eliminations Are Team-Level',description:'Why official competitive data cannot reliably assign every FNCS elimination to one player and how FantaFort handles the limitation.',sections:[
  {title:'What the public data contains',paragraphs:['Tournament leaderboard sessions expose a TEAM_ELIMS statistic for the leaderboard entry. In duo, trio or squad formats, that entry represents the formation, not an individual kill feed. Epic account identifiers show who played together, but they do not split that team total between teammates.','Session history can also expose placement, match number, survival time and whether the team won. Those fields provide context for the formation result, but none creates a verified per-player elimination total.']},
  {title:'How to read a provider row',paragraphs:['Consider an illustrative duo session containing two Epic account IDs and TEAM_ELIMS = 12. The supported conclusion is that the duo recorded 12 eliminations in that session. It is not valid to record 12 for each player, split it automatically into six each or guess a share from the final placement.','The same boundary applies when a public leaderboard shows total tournament eliminations. Unless the provider adds an authoritative individual field, the formation remains the smallest verifiable unit.']},
  {title:'Why FantaFort does not estimate individuals',paragraphs:['Dividing eliminations equally or inventing a likely share would create false precision. A player may contribute through damage, support, survival or an elimination secured by a teammate. Without an authoritative individual field, FantaFort keeps the official team statistic and states the limitation.']},
  {title:'How league modes account for the team result',paragraphs:['Classic scoring values every selected teammate with the full official score. Balanced scoring divides points by formation size. Formation scoring counts the formation once. League owners can choose the trade-off they prefer, while the underlying source remains unchanged and auditable.','This treatment applies to the official total, not to an invented elimination split. Verified competitive rulings can remove or penalize a result only when an administrator records a reliable HTTPS source. Missing sessions or rumors are not treated as proof.']}]},
 {slug:'player-eligibility',title:'How Players Enter the FantaFort Market',description:'See which recent FNCS placements make a verified Epic account eligible for the FantaFort market and why the player pool changes.',sections:[
  {title:'Eligibility comes from recent FNCS results',paragraphs:['The market is not a popularity ranking and does not use estimated career earnings. FantaFort imports verified Epic accounts from recent FNCS windows: Division 1 top 100 in EU and NAC, Division 2–3 EU top 10, plus Italian players reaching the top 100 in those divisions.','Eligibility is attached to the Epic account returned by the competitive provider. A display-name match, social profile or community reputation alone is not enough to add a player.']},
  {title:'The qualification decision',paragraphs:['The sync first identifies an eligible division, region and recent result window. It then checks the placement threshold for that route: top 100 for Division 1 EU/NAC, top 10 for Division 2–3 EU, or the documented Italian top-100 exception. Only entries with a usable Epic account identifier can become market players.','Meeting one route is sufficient for inclusion; combining several results does not create a higher eligibility tier. Market price and later fantasy score are separate calculations and do not change the original reason the account entered the pool.']},
  {title:'Why the pool changes',paragraphs:['Competitive form and event availability change over time. Automated synchronization reviews recent tournament windows and can add newly qualified players. A market entry therefore reflects the documented eligibility rule and available provider data, not an endorsement or permanent professional status.','Provider corrections, renamed accounts and new divisions may change what can be verified. FantaFort preserves source identifiers and refresh timestamps so changes can be traced instead of silently filling gaps.']},
  {title:'Missing profile information',paragraphs:['Osirion supplies results and account identifiers, not biographies or guaranteed headshots. Missing age, earnings, team or image data is shown as unavailable. Selected marquee profiles use separately sourced snapshots with attribution; nothing is fabricated to make a card look complete.','A player can therefore be eligible without a public profile page. Indexable profiles are limited to selected players with enough verified, unique data and an authorized local image.']}]},
 {slug:'standings-and-projections',title:'How to Read FantaFort Standings and Projections',description:'A field-by-field explanation of live points, projections, synergy, strategy bonuses and data freshness.',sections:[
  {title:'Base points versus fantasy additions',paragraphs:['Base is the score derived from the official tournament result under the league’s chosen mode. Synergy rewards selected teammates according to the documented formation rule. Strategy shows captain or prediction bonuses locked before the event. Verified rulings are displayed separately rather than hidden inside the total.']},
  {title:'A projection is not an official result',paragraphs:['When a tournament has a known match cap, FantaFort can project the current pace across the remaining games. It is a simple estimate based on points per completed match, not a prediction model and not a guarantee. The official total remains the value used for final scoring.']},
  {title:'Check the timestamps',paragraphs:['League dashboards poll about every 30 seconds, while provider data normally synchronizes about every 15 minutes. A dashboard refresh cannot create results that the provider has not published yet. Delays, corrections and tournament adjudication can change a displayed result later.']}]},
 {slug:'data-and-price-updates',title:'How FantaFort Updates Results and Player Prices',description:'The sources, refresh intervals and safeguards behind tournament scores and virtual market prices.',sections:[
  {title:'Tournament synchronization',paragraphs:['FantaFort reads tournament definitions, windows, leaderboards, account identifiers and session history from the public Osirion API. Automated synchronization runs approximately every 15 minutes. The interface may poll more frequently, but it always reflects the latest completed provider import.']},
  {title:'Virtual price updates',paragraphs:['Player prices use recent competitive form from the latest available events. They are gameplay values, not financial assets, earnings estimates or betting odds. The server validates the current price when an order is submitted and pauses trading when market data is stale.']},
  {title:'Corrections and safeguards',paragraphs:['Provider corrections can update historical results. Scores count only for events starting after acquisition. Cheating penalties are never inferred from missing sessions; they require a verified ruling and source. These rules favor traceability over pretending that public data is more complete than it is.']}]}
];

const it:Guide[]=[
 {slug:'fortnite-fantasy-league',title:'Come funziona una fantasy league di Fortnite',description:'Guida pratica a rosa, budget virtuale e punteggi basati sui risultati reali FNCS.',sections:[
  {title:'L’idea di base',paragraphs:['Una fantasy league di Fortnite trasforma i risultati competitivi in una sfida tra manager. Ogni partecipante acquista pro player reali e riceve punti quando quei player disputano un evento valido.','Le leghe FantaFort sono private. Il proprietario sceglie budget virtuale, dimensione della rosa, durata del mercato, durata della lega e modalità di punteggio. I player sono esclusivi nella stessa lega.']},
  {title:'Acquisti senza punti retroattivi',paragraphs:['Un risultato conta soltanto se il torneo inizia dopo l’acquisto del player. Non è quindi possibile comprare il vincitore di ieri e ottenere punti già conquistati. I coin sono esclusivamente virtuali, non acquistabili e senza cash-out.']},
  {title:'Come si determina il vincitore',paragraphs:['I punti ufficiali costituiscono la base. La lega può assegnarli per intero, dividerli per la dimensione del team o contare una formazione una sola volta. Intesa e pronostici aggiungono bonus limitati. Vince il manager con il punteggio valido più alto alla chiusura.']}]},
 {slug:'fncs-scoring-guide',title:'Guida al punteggio fantasy FNCS',description:'Scopri come i punti FNCS ufficiali diventano punteggi fantasy classici, bilanciati o per formazione, con un esempio duo completo.',sections:[
  {title:'Si parte dalla classifica ufficiale',paragraphs:['FantaFort importa i punti pubblicati per ogni voce della leaderboard, insieme a regole di piazzamento, eliminazioni e sessioni disponibili. Quel totale ufficiale è la base di ogni modalità fantasy.','La voce appartiene alla formazione ufficiale. In duo o trio ogni account verificato è collegato allo stesso risultato del team: FantaFort modifica soltanto il modo in cui la lega privata lo assegna.']},
  {title:'Tre modalità per i punti del team',paragraphs:['La modalità classica assegna tutto il punteggio a ogni componente selezionato. La bilanciata divide i punti per il numero di componenti ufficiali per ciascun player scelto. La modalità formazioni raggruppa i teammate e conta la squadra ufficiale una sola volta per manager.','Le eliminazioni pubbliche sono del team: nessuna modalità può ricostruire con certezza chi ha realizzato ogni eliminazione. La scelta riguarda il design della lega, non modifica il dato FNCS.']},
  {title:'Esempio completo con un duo',paragraphs:['Supponiamo che un duo ottenga 240 punti ufficiali. Se un manager possiede entrambi i teammate, la modalità classica assegna 480 punti base, la bilanciata 240 e la modalità formazioni 240.','Se il manager possiede un solo componente, classica assegna 240, bilanciata 120 e formazioni 240. L’esempio precede intesa, bonus strategici e penalità verificate; il sito usa sempre il totale realmente importato.']},
  {title:'Bonus, proiezioni e tempistiche',paragraphs:['Il capitano aggiunge il 10%. Pronostici compagno e punteggio esatto sono limitati. Tutte le scelte si bloccano all’inizio dell’evento e gli acquisti successivi non ricevono punti retroattivi.','La proiezione live può estendere il ritmo punti per match fino al match cap noto. Rimane separata dal risultato ufficiale e può cambiare dopo una correzione del provider.']}]},
 {slug:'team-eliminations',title:'Perché le eliminazioni FNCS sono del team',description:'Perché i dati FNCS pubblici non attribuiscono ogni eliminazione al singolo player e come FantaFort gestisce il limite.',sections:[
  {title:'Cosa espone il dato pubblico',paragraphs:['Le sessioni della leaderboard espongono TEAM_ELIMS per la voce di classifica. Nei formati duo, trio o squad quella voce rappresenta la formazione, non il kill feed individuale. Gli account Epic indicano i compagni ma non dividono il totale.','Lo storico può includere anche piazzamento, numero del match, tempo di sopravvivenza e vittoria. Sono informazioni utili sul risultato del team, ma non producono una statistica individuale verificata.']},
  {title:'Come leggere una riga del provider',paragraphs:['Immaginiamo una sessione duo con due account Epic e TEAM_ELIMS = 12. Possiamo affermare soltanto che il duo ha ottenuto 12 eliminazioni: non 12 a testa, non sei a testa e neppure una divisione stimata dal piazzamento.','Lo stesso limite vale per il totale del torneo. Finché il provider non espone un campo individuale autorevole, la formazione è l’unità minima verificabile.']},
  {title:'Perché non stimiamo le eliminazioni individuali',paragraphs:['Dividere automaticamente o ipotizzare le eliminazioni produrrebbe una precisione falsa. Un player può contribuire con danno, supporto o sopravvivenza mentre il teammate conclude l’eliminazione. FantaFort conserva quindi il dato di squadra e dichiara il limite.']},
  {title:'Le opzioni per la lega',paragraphs:['Classica assegna il totale a ogni teammate, bilanciata lo divide, formazioni conta la squadra una volta. Il proprietario sceglie il compromesso, mentre la fonte rimane invariata e verificabile.','Una penalità modifica il risultato soltanto dopo un provvedimento verificato con fonte HTTPS. Sessioni mancanti o voci della community non vengono trattate come prova.']}]},
 {slug:'player-eligibility',title:'Come vengono scelti i player di FantaFort',description:'Scopri quali piazzamenti FNCS rendono un account Epic idoneo al mercato FantaFort e perché il pool cambia nel tempo.',sections:[
  {title:'Contano i risultati FNCS recenti',paragraphs:['Il mercato non è una classifica di popolarità e non usa earnings stimati. Include top 100 Division 1 EU/NAC, top 10 Division 2–3 EU e player italiani in top 100 nelle stesse divisioni, usando account Epic verificati.','L’idoneità appartiene all’account Epic restituito dal provider competitivo. Somiglianze nel nome, profili social o reputazione nella community non bastano per inserire un player.']},
  {title:'Il percorso di qualificazione',paragraphs:['Il sync identifica divisione, regione e finestra recente, poi applica la soglia corretta: top 100 Division 1 EU/NAC, top 10 Division 2–3 EU oppure eccezione italiana top 100. Serve inoltre un identificativo Epic utilizzabile.','È sufficiente soddisfare un percorso. Più risultati non creano un livello di idoneità superiore: prezzo di mercato e punteggio fantasy sono calcoli separati.']},
  {title:'Perché il pool cambia',paragraphs:['Forma competitiva ed eventi cambiano. Il sync automatico riesamina le finestre recenti e può aggiungere nuovi qualificati. L’idoneità applica una regola documentata, non rappresenta un endorsement permanente.','Correzioni del provider, account rinominati e nuove divisioni possono modificare ciò che è verificabile. FantaFort conserva identificativi e orari di aggiornamento per rendere i cambiamenti tracciabili.']},
  {title:'Informazioni mancanti',paragraphs:['Osirion fornisce risultati e account, non biografie o headshot. Età, earnings, team e immagini mancanti vengono indicati come non disponibili. Nessun dato viene inventato.','Un player può essere idoneo senza avere un profilo pubblico. Le pagine indicizzabili restano limitate ai player con dati unici verificati e un’immagine locale autorizzata.']}]},
 {slug:'standings-and-projections',title:'Come leggere classifica e proiezioni FantaFort',description:'Significato di punti base, proiezione, intesa, strategie e tempi di aggiornamento.',sections:[
  {title:'Punti base e bonus fantasy',paragraphs:['Base deriva dal risultato ufficiale secondo la modalità scelta. Intesa applica la regola sulle formazioni. Strategia mostra capitano e pronostici bloccati prima dell’evento. I provvedimenti verificati restano separati.']},
  {title:'La proiezione non è un risultato',paragraphs:['Con un match cap noto, FantaFort estende il ritmo corrente alle partite residue. È una stima semplice basata sui punti per match, non un modello predittivo. Il punteggio ufficiale rimane quello definitivo.']},
  {title:'Controlla gli orari',paragraphs:['La dashboard interroga i dati circa ogni 30 secondi, mentre il provider viene sincronizzato circa ogni 15 minuti. Ritardi, correzioni e decisioni del torneo possono modificare il risultato.']}]},
 {slug:'data-and-price-updates',title:'Come si aggiornano risultati e prezzi FantaFort',description:'Fonti, frequenza e salvaguardie dei punteggi torneo e dei prezzi virtuali.',sections:[
  {title:'Sincronizzazione dei tornei',paragraphs:['FantaFort legge definizioni, finestre, leaderboard, account e sessioni dall’API pubblica Osirion. Il sync automatico avviene circa ogni 15 minuti; il polling dell’interfaccia non può anticipare un’importazione.']},
  {title:'Aggiornamento dei prezzi virtuali',paragraphs:['I prezzi riflettono la forma competitiva recente. Sono valori di gioco, non asset finanziari, earnings o quote. Il server verifica il prezzo al momento dell’ordine e sospende il mercato se i dati sono obsoleti.']},
  {title:'Correzioni e garanzie',paragraphs:['Le correzioni del provider possono aggiornare risultati storici. Contano solo eventi successivi all’acquisto. Penalità per cheating richiedono un provvedimento verificato e non vengono dedotte da sessioni mancanti.']}]}
];

export const guides={en,it};
export function getGuide(locale:GuideLocale,slug:string){return guides[locale].find(guide=>guide.slug===slug)}
