"use client";

import MarketingFooter from '@/components/MarketingFooter';
import MarketingHeader from '@/components/MarketingHeader';
import { useLocale } from '@/context/LocaleContext';
import { Locale } from '@/lib/i18n';
import { DISCORD_INVITE_URL, PRIVACY_EMAIL, SECURITY_EMAIL, SUPPORT_EMAIL } from '@/lib/legal';

const copy:Record<Locale,{title:string;intro:string;general:string;privacy:string;security:string;discord:string;join:string;safe:string}>={
  en:{title:'Support',intro:'FantaFort is operated as a limited free alpha. Describe the problem, affected page and approximate time.',general:'Game, league and account support',privacy:'Privacy and account-deletion requests',security:'Private vulnerability reports',discord:'Use the verified official Discord below for private support tickets. Do not trust invitations sent by unknown users.',join:'Join the official Discord',safe:'Never send passwords, recovery codes, session tokens, API keys or identity documents in a Discord ticket or email.'},
  it:{title:'Supporto',intro:'FantaFort è gestito come alpha gratuita limitata. Descrivi il problema, la pagina interessata e l’orario approssimativo.',general:'Supporto gioco, leghe e account',privacy:'Richieste privacy e cancellazione account',security:'Segnalazioni private di vulnerabilità',discord:'Usa il Discord ufficiale verificato qui sotto per i ticket privati. Non fidarti di inviti inviati da utenti sconosciuti.',join:'Entra nel Discord ufficiale',safe:'Non inviare mai password, codici di recupero, token di sessione, chiavi API o documenti di identità tramite Discord o email.'},
  es:{title:'Soporte',intro:'FantaFort funciona como alpha gratuita limitada. Describe el problema, página y hora aproximada.',general:'Juego, ligas y cuenta',privacy:'Privacidad y eliminación de cuenta',security:'Vulnerabilidades privadas',discord:'Usa el Discord oficial verificado para los tickets privados.',join:'Únete al Discord oficial',safe:'Nunca envíes contraseñas, códigos, tokens, claves API ni documentos.'},
  de:{title:'Support',intro:'FantaFort ist eine begrenzte kostenlose Alpha. Beschreibe Problem, Seite und ungefähre Uhrzeit.',general:'Spiel, Ligen und Konto',privacy:'Datenschutz und Kontolöschung',security:'Vertrauliche Sicherheitsmeldungen',discord:'Nutze den bestätigten offiziellen Discord für private Support-Tickets.',join:'Offiziellem Discord beitreten',safe:'Sende niemals Passwörter, Codes, Tokens, API-Schlüssel oder Ausweisdokumente.'},
  fr:{title:'Support',intro:'FantaFort est une alpha gratuite limitée. Décrivez le problème, la page et l’heure approximative.',general:'Jeu, ligues et compte',privacy:'Confidentialité et suppression de compte',security:'Signalements privés de vulnérabilité',discord:'Utilisez le Discord officiel vérifié pour les tickets privés.',join:'Rejoindre le Discord officiel',safe:'N’envoyez jamais mots de passe, codes, jetons, clés API ou pièces d’identité.'},
};

export default function SupportPage(){const{locale}=useLocale();const text=copy[locale];const row=(label:string,email:string)=><li><strong>{label}:</strong> <a href={`mailto:${email}`}>{email}</a></li>;return <div className="app-shell"><MarketingHeader locale={locale}/><main className="container page-content legal-page"><div className="page-title"><div className="eyebrow">FANTAFORT</div><h1>{text.title}</h1><p>{text.intro}</p></div><section className="epic-panel"><ul>{row(text.general,SUPPORT_EMAIL)}{row(text.privacy,PRIVACY_EMAIL)}{row(text.security,SECURITY_EMAIL)}</ul></section><section className="epic-panel"><h2>Discord</h2><p>{text.discord}</p><p><a href={DISCORD_INVITE_URL} target="_blank" rel="noreferrer">{text.join}</a></p></section><p className="notice">{text.safe}</p></main><MarketingFooter locale={locale}/></div>}
