"use client";

import MarketingFooter from '@/components/MarketingFooter';
import MarketingHeader from '@/components/MarketingHeader';
import { useLocale } from '@/context/LocaleContext';
import { Locale } from '@/lib/i18n';

type Copy = { title:string; intro:string; noTracking:string; inventory:string; name:string; purpose:string; duration:string; browser:string; manage:string; manageText:string; future:string; rows:[string,string,string][] };
const copy: Record<Locale, Copy> = {
  en:{title:'Cookie and storage notice',intro:'Updated 17 July 2026. FantaFort uses only technical storage needed to operate the game and remember user choices.',noTracking:'No analytics, advertising, profiling or third-party marketing cookies are installed.',inventory:'Storage inventory',name:'Name',purpose:'Purpose',duration:'Duration',browser:'Technology',manage:'How to manage it',manageText:'Use your browser settings to inspect or delete cookies and site data. Deleting authentication storage signs you out; deleting preferences shows the guide and cookie notice again.',future:'If optional analytics or marketing tools are added later, they will remain disabled until explicit consent is collected.',rows:[['fantafort_cookie_notice','Remembers that this notice was read','180 days'],['fantafort-locale / fantafort-league','Language and selected league preferences','Until deleted'],['fantafort-guide-v1:*','Remembers completion of the first-use guide','Until deleted'],['fantafort-game','Demo roster when Supabase is unavailable','Until deleted'],['Supabase auth storage','Keeps an authenticated session securely on this device','Until logout, expiry or deletion']]},
  it:{title:'Informativa cookie e memoria locale',intro:'Aggiornata il 17 luglio 2026. FantaFort usa soltanto dati tecnici necessari al funzionamento e per ricordare le scelte dell’utente.',noTracking:'Non vengono installati cookie analitici, pubblicitari, di profilazione o marketing di terze parti.',inventory:'Elenco dei dati salvati',name:'Nome',purpose:'Finalità',duration:'Durata',browser:'Tecnologia',manage:'Come gestirli',manageText:'Usa le impostazioni del browser per controllare o cancellare cookie e dati del sito. Eliminando l’autenticazione uscirai dall’account; eliminando le preferenze ricompariranno guida e avviso cookie.',future:'Se in futuro verranno aggiunti strumenti analitici o di marketing opzionali, resteranno disattivati fino a un consenso esplicito.',rows:[['fantafort_cookie_notice','Ricorda la lettura di questo avviso','180 giorni'],['fantafort-locale / fantafort-league','Preferenze di lingua e lega selezionata','Fino alla cancellazione'],['fantafort-guide-v1:*','Ricorda il completamento della guida iniziale','Fino alla cancellazione'],['fantafort-game','Rosa demo quando Supabase non è disponibile','Fino alla cancellazione'],['Memoria autenticazione Supabase','Mantiene la sessione autenticata sul dispositivo','Fino a logout, scadenza o cancellazione']]},
  es:{title:'Aviso de cookies y almacenamiento',intro:'Actualizado el 17 de julio de 2026. Solo se guardan datos técnicos y preferencias necesarias.',noTracking:'No hay cookies analíticas, publicitarias ni de perfilado.',inventory:'Inventario',name:'Nombre',purpose:'Finalidad',duration:'Duración',browser:'Tecnología',manage:'Cómo gestionarlos',manageText:'Puedes borrar cookies y datos desde el navegador. Borrar la autenticación cierra la sesión; borrar preferencias vuelve a mostrar avisos.',future:'Las futuras herramientas opcionales permanecerán desactivadas hasta obtener consentimiento explícito.',rows:[['fantafort_cookie_notice','Recuerda que se leyó el aviso','180 días'],['fantafort-locale / fantafort-league','Idioma y liga seleccionada','Hasta borrado'],['fantafort-guide-v1:*','Guía inicial completada','Hasta borrado'],['fantafort-game','Plantilla de demostración','Hasta borrado'],['Almacenamiento de Supabase','Mantiene la sesión autenticada','Hasta cierre, caducidad o borrado']]},
  de:{title:'Cookie- und Speicherhinweis',intro:'Aktualisiert am 17. Juli 2026. Nur technisch notwendige Daten und Einstellungen werden gespeichert.',noTracking:'Keine Analyse-, Werbe- oder Profiling-Cookies.',inventory:'Speicherübersicht',name:'Name',purpose:'Zweck',duration:'Dauer',browser:'Technik',manage:'Verwaltung',manageText:'Cookies und Websitedaten können im Browser gelöscht werden. Auth-Daten löschen meldet ab; Einstellungen löschen zeigt Hinweise erneut.',future:'Künftige optionale Werkzeuge bleiben bis zur ausdrücklichen Zustimmung deaktiviert.',rows:[['fantafort_cookie_notice','Gelesenen Hinweis merken','180 Tage'],['fantafort-locale / fantafort-league','Sprache und Liga','Bis gelöscht'],['fantafort-guide-v1:*','Abgeschlossene Anleitung','Bis gelöscht'],['fantafort-game','Demo-Kader','Bis gelöscht'],['Supabase-Auth-Speicher','Angemeldete Sitzung','Bis Abmeldung, Ablauf oder Löschung']]},
  fr:{title:'Avis cookies et stockage',intro:'Mis à jour le 17 juillet 2026. Seules les données techniques et préférences nécessaires sont stockées.',noTracking:'Aucun cookie analytique, publicitaire ou de profilage.',inventory:'Inventaire',name:'Nom',purpose:'Finalité',duration:'Durée',browser:'Technologie',manage:'Gestion',manageText:'Supprimez cookies et données dans le navigateur. Effacer l’authentification déconnecte; effacer les préférences réaffiche les avis.',future:'Tout futur outil optionnel restera désactivé avant consentement explicite.',rows:[['fantafort_cookie_notice','Mémorise la lecture de l’avis','180 jours'],['fantafort-locale / fantafort-league','Langue et ligue choisie','Jusqu’à suppression'],['fantafort-guide-v1:*','Guide initial terminé','Jusqu’à suppression'],['fantafort-game','Équipe de démonstration','Jusqu’à suppression'],['Stockage Supabase Auth','Maintient la session connectée','Déconnexion, expiration ou suppression']]},
};

export default function CookiesPage() {
  const { locale } = useLocale(); const text = copy[locale];
  return <div className="app-shell"><MarketingHeader locale={locale}/><main className="container page-content legal-page"><div className="page-title"><div className="eyebrow">LEGAL</div><h1>{text.title}</h1><p>{text.intro}</p></div>
    <p className="notice">{text.noTracking}</p>
    <section className="epic-panel"><h2>{text.inventory}</h2><div className="table-wrap"><table><thead><tr><th>{text.name}</th><th>{text.purpose}</th><th>{text.browser}</th><th>{text.duration}</th></tr></thead><tbody>{text.rows.map(([name,purpose,duration],index)=><tr key={name}><td><code>{name}</code></td><td>{purpose}</td><td>{index === 0 ? 'Cookie' : 'localStorage'}</td><td>{duration}</td></tr>)}</tbody></table></div></section>
    <section className="epic-panel"><h2>{text.manage}</h2><p>{text.manageText}</p><p>{text.future}</p></section>
  </main><MarketingFooter locale={locale}/></div>;
}
