import Link from 'next/link';
import type { Guide, GuideLocale } from '@/lib/guides';
import { guides } from '@/lib/guides';
import MarketingFooter from './MarketingFooter';
import MarketingHeader from './MarketingHeader';

export default function GuideArticle({guide,locale}:{guide:Guide;locale:GuideLocale}){
  const path=`${locale==='it'?'/it':''}/guides/${guide.slug}`;
  const schema={'@context':'https://schema.org','@type':'Article',headline:guide.title,description:guide.description,image:'https://fantafort.com/opengraph-image',datePublished:'2026-07-18',dateModified:'2026-07-18',inLanguage:locale,mainEntityOfPage:`https://fantafort.com${path}`,author:{'@type':'Organization',name:'FantaFort',url:'https://fantafort.com/about'},publisher:{'@type':'Organization',name:'FantaFort',url:'https://fantafort.com/'}};
  const crumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'FantaFort',item:'https://fantafort.com/'},{'@type':'ListItem',position:2,name:locale==='it'?'Guide':'Guides',item:`https://fantafort.com${locale==='it'?'/it':''}/guides`},{'@type':'ListItem',position:3,name:guide.title,item:`https://fantafort.com${path}`}]};
  return <div className="marketing-shell" lang={locale}><MarketingHeader locale={locale}/><main className="marketing-article guide-article"><header><div className="eyebrow">FANTAFORT · {locale==='it'?'GUIDA':'GUIDE'}</div><h1>{guide.title}</h1><p>{guide.description}</p><time dateTime="2026-07-18">{locale==='it'?'Aggiornata il 18 luglio 2026':'Updated 18 July 2026'}</time></header>{guide.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</section>)}<section className="guide-sources"><h2>{locale==='it'?'Fonti e metodologia':'Sources and methodology'}</h2><p>{locale==='it'?'I risultati competitivi provengono da Osirion. Regole e limiti implementati sono documentati nella pagina Come funziona.':'Competitive results come from Osirion. Implemented rules and data limits are documented on the How it works page.'}</p><p><a href="https://fnapi.osirion.gg" target="_blank" rel="noreferrer">Osirion API</a> · <Link href={locale==='it'?'/it/how-it-works':'/how-it-works'}>{locale==='it'?'Come funziona':'How it works'}</Link></p></section><aside className="related-guides"><h2>{locale==='it'?'Guide correlate':'Related guides'}</h2>{guides[locale].filter(item=>item.slug!==guide.slug).slice(0,3).map(item=><Link key={item.slug} href={`${locale==='it'?'/it':''}/guides/${item.slug}`}>{item.title} →</Link>)}</aside></main><MarketingFooter locale={locale}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replaceAll('<','\\u003c')}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs).replaceAll('<','\\u003c')}}/></div>
}
