import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import MarketingFooter from '@/components/MarketingFooter';
import MarketingHeader from '@/components/MarketingHeader';
import { photoCredit } from '@/lib/photo-credits';
import { featuredPlayerIds, getFeaturedPlayer } from '@/lib/public-players';

export const revalidate=900;
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const player=await getFeaturedPlayer(slug);if(!player)return{robots:{index:false,follow:false}};const name=player.real_name||player.handle;const description=`${name} competitive Fortnite profile: recent tournament points, placements, win rate and sourced career snapshot.`;return{title:`${name} Fortnite Stats`,description,alternates:{canonical:`/players/${slug}`},openGraph:{title:`${name} Fortnite Stats | FantaFort`,description,url:`/players/${slug}`,images:player.photo_url?[{url:player.photo_url,alt:`${name} Fortnite player`}]:undefined}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;if(!featuredPlayerIds.includes(slug as typeof featuredPlayerIds[number]))notFound();const player=await getFeaturedPlayer(slug);if(!player)notFound();const name=player.real_name||player.handle;const stats=[['Recent tournament points',player.tournament_points.toLocaleString('en')],['Events in sample',String(player.cups_played)],['Wins in sample',String(player.tournament_wins)],['Best placement',player.best_placement?`#${player.best_placement}`:'Unavailable'],['Average placement',player.average_placement?.toFixed(1)||'Unavailable'],['Points per match',player.points_per_match.toFixed(1)],['Win rate',`${player.win_rate.toFixed(1)}%`],['Career earnings snapshot',player.earnings?`$${player.earnings.toLocaleString('en')}`:'Unavailable']];const schema={'@context':'https://schema.org','@type':'ProfilePage',name:`${name} Fortnite competitive profile`,url:`https://fantafort.com/players/${slug}`,dateModified:'2026-07-18',mainEntity:{'@type':'Person',name,alternateName:player.handle,birthDate:player.birth_date||undefined,affiliation:player.organization?{'@type':'Organization',name:player.organization}:undefined,image:`https://fantafort.com${player.photo_url}`}};return <div className="marketing-shell"><MarketingHeader locale="en"/><main className="marketing-article player-profile"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/players">Players</Link><span>→</span><span>{name}</span></nav><header><div><div className="eyebrow">{player.organization||'FORTNITE PRO'}</div><h1>{name}</h1><p>{player.handle} is included in the FantaFort market through documented recent FNCS eligibility. Statistics below cover the currently imported competitive sample, not the player’s full career.</p></div><figure className="player-photo"><Image src={player.photo_url!} alt={`${name} competitive Fortnite player`} width={520} height={520} priority/><figcaption>{photoCredit(slug).text} · <Link href="/credits">Credits</Link></figcaption></figure></header><section><h2>Recent competitive statistics</h2><div className="profile-stat-grid">{stats.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section><section><h2>How to interpret this profile</h2><p>Leaderboard points and placements come from Osirion tournament data. Fortnite exposes eliminations at team level, so this page does not invent an individual elimination total. Earnings and birth date are curated Liquipedia snapshots from July 2026 and may change after that date.</p><p><Link href="/guides/player-eligibility">How player eligibility works →</Link><br/><Link href="/guides/team-eliminations">Why eliminations are team-level →</Link><br/><Link href="/tournaments">View current tournaments →</Link></p></section></main><MarketingFooter locale="en"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replaceAll('<','\\u003c')}}/></div>}
