"use client";

import Link from 'next/link';
import MarketingFooter from '@/components/MarketingFooter';
import MarketingHeader from '@/components/MarketingHeader';
import { useLocale } from '@/context/LocaleContext';
import { Locale } from '@/lib/i18n';
import { PRIVACY_EMAIL } from '@/lib/legal';

type Copy = { title:string; intro:string; controller:string; sections:{title:string;body:string;items?:string[]}[]; request:string; deletion:string; authority:string };
const copy:Record<Locale,Copy>={
  en:{title:'Privacy notice',intro:'Effective 24 July 2026. This notice explains how the free FantaFort public alpha handles personal data.',controller:'Controller: the independent FantaFort project operator, based in Italy. Privacy contact:',sections:[
    {title:'Data we process',body:'We process only what is needed to provide and secure the service.',items:['Account email and authentication records managed by Supabase; FantaFort never receives your password in readable form.','Username, language, account status and game activity, including leagues, friends, virtual wallet entries, rosters and rewards.','Limited technical and security information produced by Supabase, Vercel and application error logs.','Messages you voluntarily send to support.']},
    {title:'Purposes and legal bases',body:'Account and game data is processed to provide the service you request. Security, abuse prevention, debugging and game-integrity checks rely on our legitimate interest in operating a safe and reliable alpha. Legal obligations apply where required. FantaFort does not use advertising, profiling or marketing analytics.'},
    {title:'Providers and transfers',body:'Supabase provides authentication and database services; Vercel hosts the application; GitHub Actions performs scheduled data synchronization; Osirion supplies public competitive results. These providers may process technical data outside the EEA under their applicable contractual safeguards. We do not sell personal data.'},
    {title:'Retention',body:'Account data is kept while the account is active and until a verified deletion request is completed. Security, audit and virtual-wallet records may be retained in pseudonymized form when necessary to preserve integrity, prevent fraud or meet legal obligations. Operational logs are kept only for as long as reasonably needed for security and debugging.'},
    {title:'Your rights',body:'Depending on applicable law, you may request access, correction, deletion, restriction, portability or object to processing. You may also complain to the Italian Data Protection Authority or your local supervisory authority.'},
    {title:'Children',body:'The public alpha is intended for users aged 16 or older. Do not register if you do not meet this requirement. FantaFort does not knowingly request data from younger children.'},
    {title:'Security and changes',body:'We use access controls, row-level database policies, encrypted transport and security monitoring, but no online service can guarantee absolute security. Material changes will be dated on this page.'},
  ],request:'Send privacy requests from the email registered to your account and include your username. Never send a password, recovery code or authentication token.',deletion:'Request account deletion from Account settings or by email after leaving or closing open leagues. An in-app request immediately suspends access. We then verify the request and delete or anonymize data unless retention is required for security, ledger integrity or law. Requests are normally completed within 30 days.',authority:'Italian Data Protection Authority'},
  it:{title:'Informativa privacy',intro:'In vigore dal 24 luglio 2026. Questa informativa spiega come la public alpha gratuita di FantaFort tratta i dati personali.',controller:'Titolare: il gestore indipendente del progetto FantaFort, con sede in Italia. Contatto privacy:',sections:[
    {title:'Dati trattati',body:'Trattiamo soltanto i dati necessari a fornire e proteggere il servizio.',items:['Email e dati di autenticazione gestiti da Supabase; FantaFort non riceve mai la password in forma leggibile.','Nome account, lingua, stato dell’account e attività di gioco, incluse leghe, amicizie, wallet virtuale, rose e ricompense.','Informazioni tecniche e di sicurezza limitate prodotte da Supabase, Vercel e dai log degli errori applicativi.','Messaggi inviati volontariamente al supporto.']},
    {title:'Finalità e basi giuridiche',body:'I dati dell’account e di gioco sono trattati per fornire il servizio richiesto. Sicurezza, prevenzione abusi, debug e integrità del gioco si basano sul legittimo interesse a gestire un’alpha sicura e affidabile. Si applicano gli obblighi di legge quando necessari. Non usiamo pubblicità, profilazione o analytics di marketing.'},
    {title:'Fornitori e trasferimenti',body:'Supabase fornisce autenticazione e database; Vercel ospita l’applicazione; GitHub Actions esegue la sincronizzazione programmata; Osirion fornisce risultati competitivi pubblici. Questi fornitori possono trattare dati tecnici fuori dallo SEE secondo le rispettive garanzie contrattuali. Non vendiamo dati personali.'},
    {title:'Conservazione',body:'I dati dell’account sono conservati finché l’account è attivo e fino al completamento di una richiesta verificata di cancellazione. Record di sicurezza, audit e wallet virtuale possono essere conservati in forma pseudonimizzata quando necessario per integrità, antifrode o obblighi di legge. I log operativi restano solo per il tempo ragionevolmente necessario a sicurezza e debug.'},
    {title:'Diritti',body:'Puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità o opporti al trattamento nei casi previsti. Puoi inoltre presentare reclamo al Garante per la protezione dei dati personali o alla tua autorità locale.'},
    {title:'Minori',body:'La public alpha è destinata a utenti di almeno 16 anni. Non registrarti se non soddisfi questo requisito. FantaFort non richiede consapevolmente dati a bambini più piccoli.'},
    {title:'Sicurezza e modifiche',body:'Usiamo controlli di accesso, policy database a livello di riga, trasporto cifrato e monitoraggio di sicurezza, ma nessun servizio online può garantire sicurezza assoluta. Le modifiche sostanziali saranno datate su questa pagina.'},
  ],request:'Invia le richieste privacy dall’email registrata all’account e indica il nome utente. Non inviare mai password, codici di recupero o token di autenticazione.',deletion:'Richiedi la cancellazione dalle impostazioni Account o via email dopo aver lasciato o chiuso le leghe aperte. La richiesta in-app sospende subito l’accesso. Poi verifichiamo e cancelliamo o anonimizziamo i dati, salvo conservazione necessaria per sicurezza, integrità del ledger o legge. Le richieste sono normalmente completate entro 30 giorni.',authority:'Garante per la protezione dei dati personali'},
  es:{title:'Aviso de privacidad',intro:'Vigente desde el 24 de julio de 2026. Explica cómo la alpha pública gratuita de FantaFort trata los datos personales.',controller:'Responsable: operador independiente del proyecto FantaFort, con sede en Italia. Contacto:',sections:[
    {title:'Datos tratados',body:'Tratamos únicamente los datos necesarios para prestar y proteger el servicio.',items:['Correo y autenticación gestionados por Supabase; nunca recibimos la contraseña en texto legible.','Usuario, idioma, estado y actividad de juego: ligas, amistades, monedero virtual, plantillas y recompensas.','Información técnica limitada de Supabase, Vercel y registros de errores.','Mensajes enviados voluntariamente a soporte.']},
    {title:'Finalidades y bases',body:'Los datos se usan para prestar el servicio solicitado. La seguridad, prevención de abusos, depuración e integridad se basan en nuestro interés legítimo. No usamos publicidad, perfilado ni analítica de marketing.'},
    {title:'Proveedores',body:'Supabase proporciona autenticación y base de datos; Vercel alojamiento; GitHub Actions sincronización; Osirion resultados públicos. Pueden existir transferencias fuera del EEE con las garantías contractuales aplicables. No vendemos datos.'},
    {title:'Conservación',body:'Conservamos los datos mientras la cuenta esté activa y hasta completar una solicitud verificada. Registros de seguridad, auditoría y monedero pueden mantenerse seudonimizados por integridad, fraude u obligaciones legales.'},
    {title:'Derechos',body:'Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición y reclamar ante la autoridad de protección de datos competente.'},
    {title:'Menores',body:'La alpha pública está destinada a usuarios de 16 años o más.'},
  ],request:'Escribe desde el correo registrado e indica tu usuario. Nunca envíes contraseñas, códigos ni tokens.',deletion:'Antes de solicitar la supresión, abandona o cierra las ligas abiertas. Verificaremos y completaremos normalmente la solicitud en 30 días.',authority:'Autoridad italiana de protección de datos'},
  de:{title:'Datenschutzhinweis',intro:'Gültig ab 24. Juli 2026. Dieser Hinweis erklärt die Verarbeitung personenbezogener Daten in der kostenlosen öffentlichen Alpha.',controller:'Verantwortlicher: unabhängiger Betreiber des Projekts FantaFort mit Sitz in Italien. Kontakt:',sections:[
    {title:'Verarbeitete Daten',body:'Wir verarbeiten nur Daten, die für Betrieb und Schutz erforderlich sind.',items:['E-Mail und Anmeldung über Supabase; Passwörter liegen FantaFort nie lesbar vor.','Benutzername, Sprache, Kontostatus und Spielaktivität wie Ligen, Freunde, virtuelle Wallet, Kader und Belohnungen.','Begrenzte technische Daten von Supabase, Vercel und Fehlerprotokollen.','Freiwillige Supportnachrichten.']},
    {title:'Zwecke und Grundlagen',body:'Kontodaten dienen der Vertragserfüllung. Sicherheit, Missbrauchsschutz, Fehleranalyse und Spielintegrität beruhen auf berechtigtem Interesse. Keine Werbung, Profilbildung oder Marketing-Analyse.'},
    {title:'Dienstleister',body:'Supabase stellt Authentifizierung und Datenbank bereit, Vercel das Hosting, GitHub Actions die Synchronisierung und Osirion öffentliche Ergebnisse. Übermittlungen außerhalb des EWR können unter den jeweiligen vertraglichen Garantien erfolgen. Daten werden nicht verkauft.'},
    {title:'Speicherung',body:'Daten bleiben bis zur bestätigten Löschanfrage gespeichert. Sicherheits-, Audit- und virtuelle Wallet-Daten können aus Integritäts-, Betrugs- oder Rechtspflichten pseudonymisiert aufbewahrt werden.'},
    {title:'Rechte',body:'Du kannst Auskunft, Berichtigung, Löschung, Einschränkung, Übertragbarkeit oder Widerspruch verlangen und dich bei einer Datenschutzbehörde beschweren.'},
    {title:'Minderjährige',body:'Die öffentliche Alpha ist für Personen ab 16 Jahren bestimmt.'},
  ],request:'Schreibe von der registrierten E-Mail-Adresse und nenne deinen Benutzernamen. Sende niemals Passwörter, Codes oder Tokens.',deletion:'Verlasse oder schließe zuerst offene Ligen. Bestätigte Anfragen werden normalerweise innerhalb von 30 Tagen bearbeitet.',authority:'Italienische Datenschutzbehörde'},
  fr:{title:'Politique de confidentialité',intro:'En vigueur le 24 juillet 2026. Ce document explique le traitement des données dans l’alpha publique gratuite.',controller:'Responsable : opérateur indépendant du projet FantaFort, établi en Italie. Contact :',sections:[
    {title:'Données traitées',body:'Nous traitons uniquement les données nécessaires au service et à sa sécurité.',items:['E-mail et authentification gérés par Supabase ; FantaFort ne reçoit jamais le mot de passe lisible.','Nom, langue, statut et activité : ligues, amis, portefeuille virtuel, équipes et récompenses.','Données techniques limitées de Supabase, Vercel et journaux d’erreurs.','Messages envoyés volontairement au support.']},
    {title:'Finalités et bases',body:'Les données servent à fournir le service demandé. Sécurité, prévention des abus, débogage et intégrité reposent sur notre intérêt légitime. Aucune publicité, profilage ou analyse marketing.'},
    {title:'Prestataires',body:'Supabase fournit authentification et base de données, Vercel l’hébergement, GitHub Actions la synchronisation et Osirion les résultats publics. Des transferts hors EEE peuvent intervenir avec les garanties contractuelles applicables. Nous ne vendons pas les données.'},
    {title:'Conservation',body:'Les données sont gardées jusqu’à la réalisation d’une demande vérifiée. Les journaux de sécurité, audit et portefeuille virtuel peuvent être conservés sous forme pseudonymisée pour intégrité, fraude ou obligation légale.'},
    {title:'Vos droits',body:'Vous pouvez demander accès, rectification, effacement, limitation, portabilité ou opposition et saisir une autorité de contrôle.'},
    {title:'Mineurs',body:'L’alpha publique est destinée aux personnes âgées de 16 ans ou plus.'},
  ],request:'Écrivez depuis l’adresse enregistrée et indiquez votre nom d’utilisateur. N’envoyez jamais mot de passe, code ou jeton.',deletion:'Quittez ou fermez d’abord les ligues ouvertes. Les demandes vérifiées sont normalement traitées sous 30 jours.',authority:'Autorité italienne de protection des données'},
};

export default function PrivacyPage(){const{locale}=useLocale();const text=copy[locale];return <div className="app-shell"><MarketingHeader locale={locale}/><main className="container page-content legal-page"><div className="page-title"><div className="eyebrow">LEGAL</div><h1>{text.title}</h1><p>{text.intro}</p></div><section className="epic-panel"><h2>{text.controller}</h2><p><a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a></p></section>{text.sections.map(section=><section className="epic-panel" key={section.title}><h2>{section.title}</h2><p>{section.body}</p>{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}</section>)}<section className="epic-panel"><h2>Privacy requests</h2><p>{text.request}</p><p>{text.deletion}</p><a className="epic-button" href={`mailto:${PRIVACY_EMAIL}?subject=${encodeURIComponent('FantaFort privacy request')}`}>{PRIVACY_EMAIL}</a></section><section className="epic-panel"><p><a href="https://www.garanteprivacy.it" target="_blank" rel="noreferrer">{text.authority}</a> · <Link href="/terms">Terms</Link> · <Link href="/cookies">Cookies</Link></p></section></main><MarketingFooter locale={locale}/></div>}
