"use client";

import Link from 'next/link';
import MarketingFooter from '@/components/MarketingFooter';
import MarketingHeader from '@/components/MarketingHeader';
import { useLocale } from '@/context/LocaleContext';
import { Locale } from '@/lib/i18n';
import { CONTROLLER_NAME, PRIVACY_EMAIL } from '@/lib/legal';

type Copy = { title:string; intro:string; controller:string; sections:{title:string;body:string;items?:string[]}[]; request:string; deletion:string; authority:string };
const copy:Record<Locale,Copy>={
  en:{title:'Privacy notice',intro:'Effective 14 August 2026. This notice explains how the free FantaFort public alpha handles personal data.',controller:`Controller: ${CONTROLLER_NAME}, independent operator of the FantaFort project, based in Italy. Privacy contact:`,sections:[
    {title:'Data we process',body:'We process only what is needed to provide and secure the service.',items:['Account email and authentication records managed by Supabase; FantaFort never receives your password in readable form.','Username, language, account status and game activity, including leagues, friends, virtual wallet entries, rosters and rewards.','Limited technical and security information produced by Supabase, Vercel and application error logs.','Messages you voluntarily send to support.']},
    {title:'Purposes and legal bases',body:'Account and game data is processed to provide the service you request. Security, abuse prevention, debugging and game-integrity checks rely on our legitimate interest in operating a safe and reliable alpha. Legal obligations apply where required. FantaFort does not use advertising, profiling or marketing analytics.'},
    {title:'Providers and transfers',body:'Supabase provides authentication and database services; Vercel hosts the application; GitHub Actions performs scheduled data synchronization; Osirion supplies public competitive results. These providers may process technical data outside the EEA under their applicable contractual safeguards. We do not sell personal data.'},
    {title:'Professional players (data not obtained from you)',body:'FantaFort also processes personal data about competitive Fortnite players who are not registered users, in order to build the game roster and calculate scores. This data is not collected from those players directly.',items:['Categories: in-game competitive handle, opaque Epic account identifier, competitive region, and public tournament placements and results. For a small number of well-known players we also show a date of birth, an earnings snapshot and a photograph.','Sources: the public Osirion competitive API, and publicly published Liquipedia player pages for the curated subset.','Legal basis: legitimate interest (art. 6(1)(f) GDPR) in operating a fantasy game built on published competitive sport results. No special categories of data are processed and no automated decision producing legal effects is taken about these players.','Retention: for as long as the player remains eligible under the published methodology; inactive accounts are removed from the roster by the following synchronization cycles.','Rights: any player may request access, rectification, erasure or object to the processing at the privacy address below. On objection we remove the player from the roster and keep the exclusion across future synchronizations, unless compelling legitimate grounds apply.']},
    {title:'Retention',body:'Account data is kept while the account is active and until a verified deletion request is completed. Security, audit and virtual-wallet records may be retained in pseudonymized form when necessary to preserve integrity, prevent fraud or meet legal obligations. Operational logs are kept only for as long as reasonably needed for security and debugging.'},
    {title:'Your rights',body:'Depending on applicable law, you may request access, correction, deletion, restriction, portability or object to processing. You may also complain to the Italian Data Protection Authority or your local supervisory authority. A machine-readable copy of your account data can be downloaded at any time from Account settings; for anything that export does not cover, write to the privacy address.'},
    {title:'Children',body:'The public alpha is intended for users aged 16 or older. Do not register if you do not meet this requirement. FantaFort does not knowingly request data from younger children.'},
    {title:'Security and changes',body:'We use access controls, row-level database policies, encrypted transport and security monitoring, but no online service can guarantee absolute security. Material changes will be dated on this page.'},
  ],request:'Send privacy requests from the email registered to your account and include your username. Never send a password, recovery code or authentication token.',deletion:'Request account deletion from Account settings or by email after leaving or closing open leagues. An in-app request immediately suspends access. We then verify the request and delete or anonymize data unless retention is required for security, ledger integrity or law. Requests are normally completed within 30 days.',authority:'Italian Data Protection Authority'},
  it:{title:'Informativa privacy',intro:'In vigore dal 14 agosto 2026. Questa informativa spiega come la public alpha gratuita di FantaFort tratta i dati personali.',controller:`Titolare del trattamento: ${CONTROLLER_NAME}, gestore indipendente del progetto FantaFort, con sede in Italia. Contatto privacy:`,sections:[
    {title:'Dati trattati',body:'Trattiamo soltanto i dati necessari a fornire e proteggere il servizio.',items:['Email e dati di autenticazione gestiti da Supabase; FantaFort non riceve mai la password in forma leggibile.','Nome account, lingua, stato dell’account e attività di gioco, incluse leghe, amicizie, wallet virtuale, rose e ricompense.','Informazioni tecniche e di sicurezza limitate prodotte da Supabase, Vercel e dai log degli errori applicativi.','Messaggi inviati volontariamente al supporto.']},
    {title:'Finalità e basi giuridiche',body:'I dati dell’account e di gioco sono trattati per fornire il servizio richiesto. Sicurezza, prevenzione abusi, debug e integrità del gioco si basano sul legittimo interesse a gestire un’alpha sicura e affidabile. Si applicano gli obblighi di legge quando necessari. Non usiamo pubblicità, profilazione o analytics di marketing.'},
    {title:'Fornitori e trasferimenti',body:'Supabase fornisce autenticazione e database; Vercel ospita l’applicazione; GitHub Actions esegue la sincronizzazione programmata; Osirion fornisce risultati competitivi pubblici. Questi fornitori possono trattare dati tecnici fuori dallo SEE secondo le rispettive garanzie contrattuali. Non vendiamo dati personali.'},
    {title:'Giocatori professionisti (dati non raccolti presso l’interessato)',body:'FantaFort tratta anche dati personali di giocatori competitivi di Fortnite che non sono utenti registrati, per costruire il listino di gioco e calcolare i punteggi. Questi dati non sono raccolti direttamente presso i giocatori.',items:['Categorie: nome competitivo in gioco, identificativo opaco dell’account Epic, regione competitiva, piazzamenti e risultati pubblici nei tornei. Per un numero ristretto di giocatori noti mostriamo anche data di nascita, montepremi e fotografia.','Fonti: l’API competitiva pubblica Osirion e le pagine giocatore pubblicate su Liquipedia per il sottoinsieme curato.','Base giuridica: legittimo interesse (art. 6.1.f GDPR) a gestire un fantasy game basato su risultati sportivi competitivi già pubblici. Non trattiamo categorie particolari di dati e non adottiamo decisioni automatizzate con effetti giuridici su questi giocatori.','Conservazione: finché il giocatore resta idoneo secondo la metodologia pubblicata; gli account inattivi escono dal listino nei cicli di sincronizzazione successivi.','Diritti: ogni giocatore può chiedere accesso, rettifica, cancellazione oppure opporsi al trattamento scrivendo all’indirizzo privacy indicato sotto. In caso di opposizione rimuoviamo il giocatore dal listino e manteniamo l’esclusione nelle sincronizzazioni successive, salvo motivi legittimi cogenti.']},
    {title:'Conservazione',body:'I dati dell’account sono conservati finché l’account è attivo e fino al completamento di una richiesta verificata di cancellazione. Record di sicurezza, audit e wallet virtuale possono essere conservati in forma pseudonimizzata quando necessario per integrità, antifrode o obblighi di legge. I log operativi restano solo per il tempo ragionevolmente necessario a sicurezza e debug.'},
    {title:'Diritti',body:'Puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità o opporti al trattamento nei casi previsti. Puoi inoltre presentare reclamo al Garante per la protezione dei dati personali o alla tua autorità locale. Una copia leggibile da macchina dei dati del tuo account è scaricabile in qualsiasi momento dalle impostazioni Account; per quanto non coperto dall’export, scrivi all’indirizzo privacy.'},
    {title:'Minori',body:'La public alpha è destinata a utenti di almeno 16 anni. Non registrarti se non soddisfi questo requisito. FantaFort non richiede consapevolmente dati a bambini più piccoli.'},
    {title:'Sicurezza e modifiche',body:'Usiamo controlli di accesso, policy database a livello di riga, trasporto cifrato e monitoraggio di sicurezza, ma nessun servizio online può garantire sicurezza assoluta. Le modifiche sostanziali saranno datate su questa pagina.'},
  ],request:'Invia le richieste privacy dall’email registrata all’account e indica il nome utente. Non inviare mai password, codici di recupero o token di autenticazione.',deletion:'Richiedi la cancellazione dalle impostazioni Account o via email dopo aver lasciato o chiuso le leghe aperte. La richiesta in-app sospende subito l’accesso. Poi verifichiamo e cancelliamo o anonimizziamo i dati, salvo conservazione necessaria per sicurezza, integrità del ledger o legge. Le richieste sono normalmente completate entro 30 giorni.',authority:'Garante per la protezione dei dati personali'},
  es:{title:'Aviso de privacidad',intro:'Vigente desde el 14 de agosto de 2026. Explica cómo la alpha pública gratuita de FantaFort trata los datos personales.',controller:`Responsable: ${CONTROLLER_NAME}, operador independiente del proyecto FantaFort, con sede en Italia. Contacto:`,sections:[
    {title:'Datos tratados',body:'Tratamos únicamente los datos necesarios para prestar y proteger el servicio.',items:['Correo y autenticación gestionados por Supabase; nunca recibimos la contraseña en texto legible.','Usuario, idioma, estado y actividad de juego: ligas, amistades, monedero virtual, plantillas y recompensas.','Información técnica limitada de Supabase, Vercel y registros de errores.','Mensajes enviados voluntariamente a soporte.']},
    {title:'Finalidades y bases',body:'Los datos se usan para prestar el servicio solicitado. La seguridad, prevención de abusos, depuración e integridad se basan en nuestro interés legítimo. No usamos publicidad, perfilado ni analítica de marketing.'},
    {title:'Proveedores',body:'Supabase proporciona autenticación y base de datos; Vercel alojamiento; GitHub Actions sincronización; Osirion resultados públicos. Pueden existir transferencias fuera del EEE con las garantías contractuales aplicables. No vendemos datos.'},
    {title:'Jugadores profesionales (datos no obtenidos del interesado)',body:'También tratamos datos de jugadores competitivos de Fortnite que no son usuarios registrados, para construir la lista de juego y calcular puntuaciones.',items:['Categorías: nombre competitivo, identificador opaco de cuenta Epic, región y resultados públicos de torneo; para pocos jugadores conocidos también fecha de nacimiento, premios y fotografía.','Fuentes: la API pública Osirion y las páginas públicas de Liquipedia.','Base jurídica: interés legítimo (art. 6.1.f RGPD) en operar un juego fantasy sobre resultados deportivos ya públicos. Sin categorías especiales ni decisiones automatizadas con efectos jurídicos.','Conservación: mientras el jugador siga siendo elegible según la metodología publicada.','Derechos: acceso, rectificación, supresión u oposición escribiendo a la dirección de privacidad. Ante una oposición retiramos al jugador de la lista y mantenemos la exclusión en las sincronizaciones futuras, salvo motivos legítimos imperiosos.']},
    {title:'Conservación',body:'Conservamos los datos mientras la cuenta esté activa y hasta completar una solicitud verificada. Registros de seguridad, auditoría y monedero pueden mantenerse seudonimizados por integridad, fraude u obligaciones legales.'},
    {title:'Derechos',body:'Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición y reclamar ante la autoridad de protección de datos competente. Puedes descargar una copia de los datos de tu cuenta desde los ajustes de Cuenta.'},
    {title:'Menores',body:'La alpha pública está destinada a usuarios de 16 años o más.'},
  ],request:'Escribe desde el correo registrado e indica tu usuario. Nunca envíes contraseñas, códigos ni tokens.',deletion:'Antes de solicitar la supresión, abandona o cierra las ligas abiertas. Verificaremos y completaremos normalmente la solicitud en 30 días.',authority:'Autoridad italiana de protección de datos'},
  de:{title:'Datenschutzhinweis',intro:'Gültig ab 14. August 2026. Dieser Hinweis erklärt die Verarbeitung personenbezogener Daten in der kostenlosen öffentlichen Alpha.',controller:`Verantwortlicher: ${CONTROLLER_NAME}, unabhängiger Betreiber des Projekts FantaFort mit Sitz in Italien. Kontakt:`,sections:[
    {title:'Verarbeitete Daten',body:'Wir verarbeiten nur Daten, die für Betrieb und Schutz erforderlich sind.',items:['E-Mail und Anmeldung über Supabase; Passwörter liegen FantaFort nie lesbar vor.','Benutzername, Sprache, Kontostatus und Spielaktivität wie Ligen, Freunde, virtuelle Wallet, Kader und Belohnungen.','Begrenzte technische Daten von Supabase, Vercel und Fehlerprotokollen.','Freiwillige Supportnachrichten.']},
    {title:'Zwecke und Grundlagen',body:'Kontodaten dienen der Vertragserfüllung. Sicherheit, Missbrauchsschutz, Fehleranalyse und Spielintegrität beruhen auf berechtigtem Interesse. Keine Werbung, Profilbildung oder Marketing-Analyse.'},
    {title:'Dienstleister',body:'Supabase stellt Authentifizierung und Datenbank bereit, Vercel das Hosting, GitHub Actions die Synchronisierung und Osirion öffentliche Ergebnisse. Übermittlungen außerhalb des EWR können unter den jeweiligen vertraglichen Garantien erfolgen. Daten werden nicht verkauft.'},
    {title:'Profispieler (nicht bei der betroffenen Person erhobene Daten)',body:'Wir verarbeiten auch Daten von kompetitiven Fortnite-Spielern, die keine registrierten Nutzer sind, um den Spielerkader aufzubauen und Punkte zu berechnen.',items:['Kategorien: kompetitiver Spielername, opake Epic-Konto-Kennung, Region sowie öffentliche Turnierergebnisse; bei wenigen bekannten Spielern zusätzlich Geburtsdatum, Preisgelder und Foto.','Quellen: die öffentliche Osirion-API und öffentlich veröffentlichte Liquipedia-Profile.','Rechtsgrundlage: berechtigtes Interesse (Art. 6 Abs. 1 lit. f DSGVO) am Betrieb eines Fantasyspiels auf Basis bereits veröffentlichter Wettkampfergebnisse. Keine besonderen Datenkategorien, keine automatisierte Entscheidung mit Rechtswirkung.','Speicherung: solange der Spieler nach der veröffentlichten Methodik qualifiziert bleibt.','Rechte: Auskunft, Berichtigung, Löschung oder Widerspruch über die Datenschutzadresse. Nach einem Widerspruch entfernen wir den Spieler aus dem Kader und halten den Ausschluss bei künftigen Synchronisierungen aufrecht, sofern keine zwingenden schutzwürdigen Gründe entgegenstehen.']},
    {title:'Speicherung',body:'Daten bleiben bis zur bestätigten Löschanfrage gespeichert. Sicherheits-, Audit- und virtuelle Wallet-Daten können aus Integritäts-, Betrugs- oder Rechtspflichten pseudonymisiert aufbewahrt werden.'},
    {title:'Rechte',body:'Du kannst Auskunft, Berichtigung, Löschung, Einschränkung, Übertragbarkeit oder Widerspruch verlangen und dich bei einer Datenschutzbehörde beschweren. Eine Kopie deiner Kontodaten kannst du jederzeit in den Kontoeinstellungen herunterladen.'},
    {title:'Minderjährige',body:'Die öffentliche Alpha ist für Personen ab 16 Jahren bestimmt.'},
  ],request:'Schreibe von der registrierten E-Mail-Adresse und nenne deinen Benutzernamen. Sende niemals Passwörter, Codes oder Tokens.',deletion:'Verlasse oder schließe zuerst offene Ligen. Bestätigte Anfragen werden normalerweise innerhalb von 30 Tagen bearbeitet.',authority:'Italienische Datenschutzbehörde'},
  fr:{title:'Politique de confidentialité',intro:'En vigueur le 14 août 2026. Ce document explique le traitement des données dans l’alpha publique gratuite.',controller:`Responsable : ${CONTROLLER_NAME}, opérateur indépendant du projet FantaFort, établi en Italie. Contact :`,sections:[
    {title:'Données traitées',body:'Nous traitons uniquement les données nécessaires au service et à sa sécurité.',items:['E-mail et authentification gérés par Supabase ; FantaFort ne reçoit jamais le mot de passe lisible.','Nom, langue, statut et activité : ligues, amis, portefeuille virtuel, équipes et récompenses.','Données techniques limitées de Supabase, Vercel et journaux d’erreurs.','Messages envoyés volontairement au support.']},
    {title:'Finalités et bases',body:'Les données servent à fournir le service demandé. Sécurité, prévention des abus, débogage et intégrité reposent sur notre intérêt légitime. Aucune publicité, profilage ou analyse marketing.'},
    {title:'Prestataires',body:'Supabase fournit authentification et base de données, Vercel l’hébergement, GitHub Actions la synchronisation et Osirion les résultats publics. Des transferts hors EEE peuvent intervenir avec les garanties contractuelles applicables. Nous ne vendons pas les données.'},
    {title:'Joueurs professionnels (données non collectées auprès de la personne concernée)',body:'Nous traitons également des données de joueurs compétitifs de Fortnite qui ne sont pas des utilisateurs inscrits, afin de constituer l’effectif de jeu et de calculer les scores.',items:['Catégories : pseudonyme compétitif, identifiant opaque de compte Epic, région et résultats publics de tournoi ; pour quelques joueurs connus, également date de naissance, gains et photographie.','Sources : l’API publique Osirion et les fiches Liquipedia publiées.','Base légale : intérêt légitime (art. 6.1.f RGPD) à exploiter un jeu fantasy fondé sur des résultats sportifs déjà publics. Aucune catégorie particulière ni décision automatisée produisant des effets juridiques.','Conservation : tant que le joueur reste éligible selon la méthodologie publiée.','Droits : accès, rectification, effacement ou opposition à l’adresse de confidentialité. En cas d’opposition, nous retirons le joueur de l’effectif et maintenons l’exclusion lors des synchronisations suivantes, sauf motifs légitimes impérieux.']},
    {title:'Conservation',body:'Les données sont gardées jusqu’à la réalisation d’une demande vérifiée. Les journaux de sécurité, audit et portefeuille virtuel peuvent être conservés sous forme pseudonymisée pour intégrité, fraude ou obligation légale.'},
    {title:'Vos droits',body:'Vous pouvez demander accès, rectification, effacement, limitation, portabilité ou opposition et saisir une autorité de contrôle. Une copie de vos données de compte est téléchargeable à tout moment depuis les paramètres du compte.'},
    {title:'Mineurs',body:'L’alpha publique est destinée aux personnes âgées de 16 ans ou plus.'},
  ],request:'Écrivez depuis l’adresse enregistrée et indiquez votre nom d’utilisateur. N’envoyez jamais mot de passe, code ou jeton.',deletion:'Quittez ou fermez d’abord les ligues ouvertes. Les demandes vérifiées sont normalement traitées sous 30 jours.',authority:'Autorité italienne de protection des données'},
};

export default function PrivacyPage(){const{locale}=useLocale();const text=copy[locale];return <div className="app-shell"><MarketingHeader locale={locale}/><main className="container page-content legal-page"><div className="page-title"><div className="eyebrow">LEGAL</div><h1>{text.title}</h1><p>{text.intro}</p></div><section className="epic-panel"><h2>{text.controller}</h2><p><a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a></p></section>{text.sections.map(section=><section className="epic-panel" key={section.title}><h2>{section.title}</h2><p>{section.body}</p>{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}</section>)}<section className="epic-panel"><h2>Privacy requests</h2><p>{text.request}</p><p>{text.deletion}</p><a className="epic-button" href={`mailto:${PRIVACY_EMAIL}?subject=${encodeURIComponent('FantaFort privacy request')}`}>{PRIVACY_EMAIL}</a></section><section className="epic-panel"><p><a href="https://www.garanteprivacy.it" target="_blank" rel="noreferrer">{text.authority}</a> · <Link href="/terms">Terms</Link> · <Link href="/cookies">Cookies</Link></p></section></main><MarketingFooter locale={locale}/></div>}
